FROM node:12.16.2-alpine as builder

WORKDIR /app

COPY . .

RUN yarn
RUN yarn build

FROM node:12.16.2-alpine

WORKDIR /app

COPY package.json .
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

EXPOSE 5000

CMD ["yarn", "start"]